before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
# - ldflags:
#   - -X 'main.BuildVersion={{.Tag}}'
#   - -X 'main.GitCommit={{.ShortCommit}}'
#   - -X 'main.BuildDate={{time "01.02.2006 15:04:05"}}'
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  name_template: "{{ .ProjectName }}_{{ .Os }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: false

brews:
- name: envsub
  github:
    owner: kruc
    name: homebrew-tap

  url_template: "https://github.com/kruc/envsub/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  commit_author:
    name: kruc
    email: jacek.ciwis@gmail.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  caveats: "Run and read"

  homepage: "https://example.com/"

  description: "Parses templates using go templates"

  skip_upload: false
