# https://taskfile.dev

version: '2'

vars:
  VERSION_TAG:
    sh: git describe --abbrev=0 --tags

tasks:
  compile:
    cmds:
      - goreleaser --snapshot --skip-publish --rm-dist

  build:
    desc: Build code
    cmds:
      - task: compile
      - cp ./dist/envsub_darwin_amd64/envsub ./

  install:
    desc: Install code
    cmds:
      - task: compile
      - cp ./dist/envsub_darwin_amd64/envsub $GOPATH/bin/envsub

  dry-release:
    desc: "Build packages"
    cmds:
      - task: compile
    silent: true

  release:
    desc: "Build packages and release"
    cmds:
      - goreleaser --rm-dist # --release-notes=releaseNotes/{{.VERSION_TAG}}.md
    silent: true

  release-notes:
    desc: "Generate release notes template"
    cmds:
      - VERSION_TAG={{.VERSION_TAG}} envsub releaseNotes/template.md --envs -o releaseNotes/{{.VERSION_TAG}}.md
    status:
      - test -f releaseNotes/{{.VERSION_TAG}}.md
